FROM ubuntu
MAINTAINER livestack.ph

# Due to terms in the Oracle license agreement, you need to
# accept the terms to download and use Oracle JDK. Get
# the link from ./java/download-java.txt
ENV JAVA_PKG      ./java/server-jre-8u*-linux-x64.tar.gz
ENV JAVA_HOME     /usr/java/default
ENV JIRA_HOME     /var/atlassian/application-data/jira
ENV JIRA_INSTALL  /opt/atlassian/jira
ENV CONF_VERSION  7.2.4

LABEL Description="This image is used to start Atlassian Jira" Vendor="Atlassian" Version="${CONF_VERSION}"

ENV JIRA_DOWNLOAD_URL https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-${CONF_VERSION}.tar.gz

# Include MySQL driver
# ENV MYSQL_VERSION 5.1.38
# ENV MYSQL_DRIVER_DOWNLOAD_URL http://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-${MYSQL_VERSION}.tar.gz

# Set the default account
ENV RUN_USER            daemon
ENV RUN_GROUP           daemon

# Copy and extract java
ADD $JAVA_PKG /usr/java/

# Install Atlassian Jira and helper tools and setup initial home
# directory structure.
RUN export JAVA_DIR=$(ls -1 -d /usr/java/*)  \
    && ln -s $JAVA_DIR /usr/java/latest \
    && ln -s $JAVA_DIR /usr/java/default \
    && update-alternatives --install /usr/bin/java java $JAVA_DIR/bin/java 20000 \
    && update-alternatives --install /usr/bin/javac javac $JAVA_DIR/bin/javac 20000 \
    && update-alternatives --install /usr/bin/jar jar $JAVA_DIR/bin/jar 20000 \
    && set -x \
    && apt-get update --quiet \
    && apt-get install --quiet --yes --no-install-recommends curl tar gzip \
    && apt-get clean all \
    && mkdir -p                           "${JIRA_INSTALL}" \
    && curl -Lks                          "${JIRA_DOWNLOAD_URL}" | tar -xz --directory "${JIRA_INSTALL}" --strip-components=1 --no-same-owner \
#   && curl -Lks                          "${MYSQL_DRIVER_DOWNLOAD_URL}" | tar -xz --directory "${JIRA_INSTALL}/lib" --strip-components=1 --no-same-owner "mysql-connector-java-${MYSQL_VERSION}/mysql-connector-java-${MYSQL_VERSION}-bin.jar" \
    && chown -R ${RUN_USER}:${RUN_GROUP}  "${JIRA_INSTALL}" \
    && chmod -R u=rwx,go-rwx              "${JIRA_INSTALL}" \
    && mkdir -p                           "${JIRA_HOME}" \
    && chown -R ${RUN_USER}:${RUN_GROUP}  "${JIRA_HOME}" \
    && chmod -R u=rwx,go-rwx              "${JIRA_HOME}"


# Use the configured account
USER ${RUN_USER}:${RUN_GROUP}

# Expose default HTTP connector port.
EXPOSE 8080

# Set volume mount points for installation and home directory. Changes to the
# home directory needs to be persisted as well as parts of the installation
# directory due to eg. logs.
VOLUME ["${JIRA_INSTALL}", "${JIRA_HOME}"]

# Set the default working directory as the Jira installation directory.
WORKDIR ${JIRA_INSTALL}

# Run Atlassian Jira as a foreground process by default.
CMD ["./bin/start-jira.sh", "run"]
