version: '2'
services:
    db:
        container_name: psql-atlassian
        image: postgres:9.5 
        env_file:
            - ./config/dbconfig.env
        volumes:
            - ./data/postgres:/var/lib/postgresql/data/pgdata
            - ./config/initdb:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"
    jira:
        container_name: jira
        image: livestackph/atlassian-jira
        build: 
            context: .
            dockerfile: Dockerfile-jira
        ports:
            - "8080:8080"
        volumes:
            - ./data/jira:/var/atlassian/application-data/jira
        depends_on:
            - db
    confluence:
        container_name: confluence
        image: livestackph/atlassian-confluence
        build: 
            context: .
            dockerfile: Dockerfile-confluence
        ports:
            - "8090:8090"
            - "8091:8091"
        volumes:
            - ./data/confluence:/var/atlassian/application-data/confluence
        depends_on:
            - db
